import QuickLook
import SwiftUI

/// «Дневник (PDF)» (#246): the БАБХ ДНЕВНИК for a location and a period,
/// generated by the server and opened in Quick Look — where it can be read,
/// shared or saved to Files.
///
/// The web offers it from a location and from a journal entry that records
/// a field operation; this is the Дневник page's own (owner, 2026-10-09:
/// «make the pdf download from journal page available»). The ДНЕВНИК is per
/// LOCATION, so the location is asked for — and chosen for the person when
/// the farm has only one. The period is the web's first offer, 1 January of
/// this year to today.
struct FarmRecordSheet: View {
    @Environment(\.dismiss) private var dismiss
    @State private var locations = LocationsStore()
    @State private var locationID: String?
    @State private var from = FarmRecordAPI.defaultPeriod().from
    @State private var to = FarmRecordAPI.defaultPeriod().to
    @State private var generating = false
    @State private var failure: String?
    /// The PDF, once generated — what Quick Look shows. Removed when the
    /// sheet closes, by its presenter (`FarmRecordAPI.removeGenerated`).
    @State private var document: URL?

    private var choices: [Location] { locations.state.value ?? [] }
    private var chosen: Location? { choices.first { $0.id == locationID } }
    private var canGenerate: Bool { !generating && chosen != nil && from <= to }

    private static let periodNote =
        "Растителнозащитните мероприятия и торенето за периода, както ги изисква БАБХ."

    var body: some View {
        NavigationStack {
            PageForm {
                Section(titled: "Локация") {
                    switch locations.state {
                    case .loading:
                        ProgressView()
                    case .failed(let message):
                        Text(message)
                            .font(.footnote)
                            .foregroundStyle(Palette.secondaryText)
                            .fixedSize(horizontal: false, vertical: true)
                    case .loaded where choices.isEmpty:
                        Text("Стопанството няма локации, за които да има дневник.")
                            .font(.footnote)
                            .foregroundStyle(Palette.secondaryText)
                            .fixedSize(horizontal: false, vertical: true)
                    case .loaded where choices.count == 1:
                        Text(choices[0].name)
                    case .loaded:
                        MenuPicker("Локация", selection: $locationID, value: chosen?.name ?? "— изберете —") {
                            Text("— изберете —").tag(String?.none)
                            ForEach(choices) { Text($0.name).tag(String?.some($0.id)) }
                        }
                    }
                }

                Section {
                    DatePicker("От", selection: $from, in: ...to, displayedComponents: .date)
                        .tint(Palette.DatePill.tint)
                    DatePicker("До", selection: $to, in: from..., displayedComponents: .date)
                        .tint(Palette.DatePill.tint)
                } header: {
                    SectionHeader("Период")
                } footer: {
                    SectionFooter {
                        // Hyphenated where AX5 has to break its first word
                        // (`SoftHyphens`); spoken as written.
                        Text(SoftHyphens.display(Self.periodNote))
                            .accessibilityLabel(Self.periodNote)
                    }
                }

                if let failure {
                    Section {
                        Text(failure)
                            .foregroundStyle(Palette.error)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
            }
            .inlineTitle("Дневник (PDF)")
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Отказ") { dismiss() }
                        .accessibilityInputLabels(A11y.Spoken.cancel)
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button {
                        Task { await generate() }
                    } label: {
                        if generating { ProgressView() } else { Text("Изтегли") }
                    }
                    .disabled(!canGenerate)
                    .accessibilityLabel("Изтегли")
                    .accessibilityInputLabels(A11y.Spoken.download)
                }
            }
            .quickLookPreview($document)
            .task {
                await locations.load()
                // Chosen for the person when there is nothing to choose.
                if locationID == nil, choices.count == 1 { locationID = choices[0].id }
            }
        }
    }

    /// The server takes up to a minute to build it — the document session
    /// waits that long (`APIClient.postForDocument`) — so the button turns
    /// into a spinner and the sheet stays.
    private func generate() async {
        guard let location = chosen, canGenerate else { return }
        generating = true
        failure = nil
        defer { generating = false }
        do {
            document = try await FarmRecordAPI.generate(locationID: location.id, from: from, to: to)
        } catch let refused as FarmRecordAPI.Failure {
            failure = refused.errorDescription
        } catch {
            failure = UserMessage.text(for: error)
        }
    }
}
