#!/bin/bash
#
# Regenerate Tests/Contract/agri-saas-routes.txt — every API path template
# agri-saas serves or has retired, which `RouteContractTests` checks the app's
# paths against (agrent-ios#132).
#
#     scripts/refresh-agri-saas-routes.sh                        # from GitHub
#     scripts/refresh-agri-saas-routes.sh ~/git/agri-saas        # local clone, at $REF
#     scripts/refresh-agri-saas-routes.sh ~/git/agri-saas HEAD   # local clone, at a ref
#     OUT=/tmp/routes.txt scripts/refresh-agri-saas-routes.sh    # write elsewhere
#
# ── The source: agri-saas's own route inventory ──
#
# `src/generated/route-inventory.json` (agri-saas#1175). The server derives it
# from its route files and keeps it APPEND-ONLY: a path that leaves the
# filesystem fails their build until someone marks it `retired` with a
# `reason`. So a rename like #130's shows up here as the old path retired and
# the new one live, with a sentence saying why — the same event that this
# app could not see from its own suite.
#
# It replaces deriving the list ourselves from `openapi.json` ∪ the
# undocumented baseline. That derivation was right (the spec describes 129 of
# 368 routes; spec alone would false-fail `/api/auth/token/refresh`), but it
# could only ever say "absent", never "retired, and here is what replaced it".
#
# The NextAuth catch-all (`/api/auth/[...nextauth]`) is deliberately NOT in
# their inventory. See `nextAuthAllowlist` in RouteContractTests.
#
# ── Why a reduced text file and not their JSON ──
#
# One line per route, byte-sorted, so a refresh diff IS the list of what the
# server added, retired or reclassified. Their file is not in byte order
# (`{` sorts after letters), so ordering is ours, not theirs. The SHA is ours
# too: the server file deliberately carries none, and a snapshot that cannot
# say which commit it describes cannot be compared with anything.
#
# Line format:  <live|retired> <documented|undocumented> <path>[ <reason>]
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

GITHUB_REPO="RodnaPamet/agri-saas"
FILE="src/generated/route-inventory.json"
# `main`: agri-saas#1175 merged, so the inventory lives there (the snapshot
# was first taken from its PR branch). Change it here and in nowhere else:
# the scheduled diff (.github/workflows/agri-saas-routes.yml) calls this script.
REF="${AGRI_SAAS_REF:-main}"
OUT="${OUT:-Tests/Contract/agri-saas-routes.txt}"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

if [ $# -ge 1 ]; then
  SRC="$1"
  REV="${2:-origin/$REF}"
  # Read from the object store at a resolved commit, never the working tree:
  # an edited, uncommitted file would be stamped with a SHA that never
  # contained it.
  SHA=$(git -C "$SRC" rev-parse --verify "$REV^{commit}")
  git -C "$SRC" show "$SHA:$FILE" > "$WORK/inventory.json"
else
  # Resolve the branch to a SHA FIRST and fetch at that SHA, so the stamp
  # names exactly the bytes read even if the branch moves mid-run.
  SHA=$(git ls-remote "https://github.com/$GITHUB_REPO.git" "refs/heads/$REF" | cut -f1)
  [ -n "$SHA" ] || { echo "error: could not resolve $GITHUB_REPO $REF" >&2; exit 1; }
  curl -fsSL --retry 3 -o "$WORK/inventory.json" \
    "https://raw.githubusercontent.com/$GITHUB_REPO/$SHA/$FILE"
fi

python3 - "$WORK/inventory.json" "$SHA" "$REF" > "$WORK/out.txt" <<'EMIT'
import json, sys

inventory_path, sha, ref = sys.argv[1:4]

def fail(msg):
    sys.stderr.write('error: %s\n' % msg)
    sys.exit(1)

# The shape is checked, not assumed: a renamed key upstream must stop this
# script, not produce an empty snapshot that fails every app path as ABSENT.
data = json.load(open(inventory_path, encoding='utf-8'))
routes = data.get('routes') if isinstance(data, dict) else None
if not isinstance(routes, list) or not routes:
    fail('route-inventory.json has no `routes` list')

rows, seen = [], set()
for r in routes:
    path, status, documented = r.get('path'), r.get('status'), r.get('documented')
    if not isinstance(path, str) or not path.startswith('/api/') or ' ' in path:
        fail('bad path: %r' % (r,))
    if status not in ('live', 'retired') or not isinstance(documented, bool):
        fail('bad status/documented: %r' % (r,))
    if path in seen:
        fail('duplicate path: %s' % path)
    seen.add(path)
    reason = ' '.join(str(r.get('reason') or '').split())
    if status == 'retired' and not reason:
        fail('retired without a reason: %s' % path)
    line = '%-7s %-12s %s' % (status, 'documented' if documented else 'undocumented', path)
    rows.append((path.encode('utf-8'), line + (' ' + reason if reason else '')))

live = sum(1 for r in routes if r['status'] == 'live')
print('# agri-saas route inventory. GENERATED by scripts/refresh-agri-saas-routes.sh; do not edit.')
print('# sha %s' % sha)
print('# from src/generated/route-inventory.json at %s: %d live, %d retired' % (ref, live, len(routes) - live))
for _, line in sorted(rows):
    print(line)
EMIT

mkdir -p "$(dirname "$OUT")"
mv "$WORK/out.txt" "$OUT"
echo "wrote $OUT from agri-saas $SHA ($(grep -vc '^#' "$OUT") routes)"
